version: '3.8'
services:
  production-db:
    image: postgres:13
    ports:
      - 5434:5432  #3306
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: production
    networks:
      - learningplanner
  development-db:
    image: postgres:13
    ports:
      - 5435:5432 #3308
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: development
    networks:
      - learningplanner
networks:
  learningplanner:
