name: checks linter
run-name: linter Actions
on: [push]
jobs:check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "14"
    - run: npm i eslint @types/eslint
    - run: npm run lint 