name: checks linter
run-name: Running linter
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install depedencies
        run: npm i

      - name: Run Build
        id: build
        run: npm build

      - name: Build Status
        if: steps.build.outcome == 'failure'
        run: exit 1

      - name: Run Eslint
        run: npm run lint
